# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of booking type, shown to users picking a meeting.', max_length=60)),
                ('slug', models.SlugField(help_text='Custom slug for meeting type, must be unique per user.', max_length=20)),
                ('duration', models.DurationField(help_text='Meeting duration, used for creating booking slots.')),
                ('padding', models.DurationField(help_text='Minimum allowed amount of time between 2 meetings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User that owns this booking type.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
