# Generated by Django 3.0.6 on 2020-05-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtype',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bookingtype',
            name='padding',
        ),
        migrations.CreateModel(
            name='BookingAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(help_text='Meeting duration, used for creating booking slots.')),
                ('padding', models.DurationField(help_text='Minimum allowed amount of time between 2 meetings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingType')),
            ],
        ),
    ]
