# Generated by Django 3.0.6 on 2020-05-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200510_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingavailability',
            name='booking_type',
            field=models.OneToOneField(help_text='Booking type associated with this model.', on_delete=django.db.models.deletion.CASCADE, to='booking.BookingType'),
        ),
    ]
